# --- Logging options ---

base_exp_path: ${run.output_dir}/json # (unused)  Base path for logging
use_console: True # Whether to log to stdout.
use_tb: False # Whether to use tensorboard logging.
use_json: False # Whether to log marl-eval style to json files.
use_neptune: False  # Whether to log to neptune.ai.
use_wandb: False  # Whether to log to wandb.ai.

# --- Other logger kwargs ---
kwargs:
  project: your/project  # Project name in neptune.ai or wandb.ai.
  name: ${run.name}
  tags: # Tags to add to the experiment.
    - ${env.reward.name}
    - ${env.agent.torso.name}${env.agent.torso.name_suffix}
    - ${env.agent.head}
    - ${env.agent.input.name}
    - ${opponents.name}
  detailed_logging: false  # (unused) having mean/std/min/max can clutter neptune/wandb so we make it optional
  json_path: null # (unused) If set, json files will be logged to a set path so that multiple experiments can
    # write to the same json file for easy downstream aggregation and plotting with marl-eval.
  upload_json_data: False # (unused) Whether JSON file data should be uploaded to Neptune/WandB for downstream
    # aggregation and plotting of data from multiple experiments. Note that when uploading JSON files,
    # `json_path` must be unset to ensure that uploaded json files don't continue getting larger
    # over time. Setting both will break.



