name: cnn
name_suffix: ""
kwargs:
  features_sizes: [64, 64, 96, 128, 96, 64, 64, 64, 64, 32]
  kernel_sizes:   [1,  1,  3,   3,   3,  3,  3,  3,  3,  3]
  strides: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  mlp_layer_sizes: [256, 256]
