name: resnet
name_suffix: 96_medium
kwargs:
  channels_per_group: [96, 64, 32]
  blocks_per_group: [2, 2, 4]
  kernels_per_group: [3, 3, 3]
  bottleneck: false
  # bottleneck_reduction_factor: 2
  n_initial_depth_convs: 1
  se_layer: true

