name: resnet
name_suffix: 96_shallow
kwargs:
  channels_per_group: [96, 64, 48]
  blocks_per_group: [1, 3, 2]
  kernels_per_group: [3, 3, 3]
  bottleneck_reduction_factor: 2
  n_initial_depth_convs: 1
  se_layer: true

