# Similar to starter, but includes elements related to winning against opponent."
defaults:
  - _base_reward
  - _self_

name: intermediate_tweaked
best_fn: episode_return
reward_coefficients:  # such that each non zero yields a return of order [0.1, 1]
  # win-related, zero-sum
  win_game: 0.0
  win_matches: 0.2 # 0 +/- 0.2
  delta_points: 0.001 # 0 +/- 0.1
  # basic game understanding
  points: 0.0005  # ~ 0.1 for 200 points cumulated
  units_energy: 0.000025  # ~ 0.1-1.0 if energy is gathered well compared to spending
  # exploration, memory_based
  tiles_explored: 0.001 # ~ 0.5 for all tiles explored
  point_tiles_found: 0.02  # ~ 0.2-0.6 for point tiles found (10-30 on average)
  relics_found: 0.08  # ~ 0.16-0.48 for relics found
  all_relics_found: 0.3  # 0.3 for all relics found
  # other based on obs/memory
  units_stuck_by_energy: -0.002  # ~ -0.1 for typical game
  point_tiles_unoccupied: -0.00025  # half the point reward
  # from lux engine, in number of units per turn (in [0, 16]), cumulated is * 505
  units_removed: 0.0
  units_moved: 0.0
  units_sapped: 0.0
  # from lux engine, sapping
  sapping_energy_benefit: 0.0  # 0.0001  # ~ 0.1
  # from lux engine, expressed as delta = player value - opponent value, defined such that a positive delta is good for the player
  delta_collision: 0.0
  delta_energy_sap: 0.0
  delta_energy_void: 0.0
  # from lux engine, other
  energy_from_field: 0.0  # 0.00001  # ~ 0.1 if favoring high energy tiles
